const { withProjectBuildGradle } = require('expo/config-plugins');

const marker = '// @generated by withAsyncStorageRepository';

module.exports = function withAsyncStorageRepository(config) {
  return withProjectBuildGradle(config, (modConfig) => {
    if (modConfig.modResults.language !== 'groovy') {
      throw new Error('withAsyncStorageRepository requires a Groovy project build.gradle');
    }

    if (!modConfig.modResults.contents.includes(marker)) {
      modConfig.modResults.contents += `
${marker}
allprojects {
  repositories {
    maven {
      url = uri(project(':react-native-async-storage_async-storage').file('local_repo'))
    }
  }
}
`;
    }

    return modConfig;
  });
};
